version: "3.8"

services:
  app:
    build: .
    container_name: housebizz-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
